### ISSUE TITLE
Cannot start in Windows.

### ISSUE THREAD

**Issue by mylvghb** [akbxr/zed-mcp-server-context7#1]
After I followed the steps in the README.md to install this extension, I couldn't start the service.

Error: Context server request timeout.

![Image](https://github.com/user-attachments/assets/1711781d-bdd1-4f14-a4c7-b584efadc276)

**Comment by akbxr** [comment]
This seems to be a network problem or an unstable zed windows build, I used mac and linux did not find a problem.

**Comment by mylvghb** [comment]
However, the context7 extensions I installed in VS Code and JetBrains can all start the service normally.

**Comment by mylvghb** [comment]
I'll try it again when the Windows version is released.

**Comment by mrstanley** [comment]
可以处理一下windows是无法使用的问题吗？

**Comment by skyp1nus** [comment]
<img width="1234" height="207" alt="Image" src="https://github.com/user-attachments/assets/0906a242-c3ac-4ded-8d95-2b92132698d9" />

same problem, last version windows nightly 
Zed Dev 0.199.0 
a884e861e98a7f9d05e344e1866d7cb144ce77dd

**Comment by Nabiyevv** [comment]
i installed it manually and works fine. 
```bash 
npm i -g @upstash/context7-mcp@latest
```

Then press"Add Cusom Server" and add 
```json
"Context7": {
   "command": "node",
   "args": [
     "C:\\Users\\<you>\\AppData\\Roaming\\npm\\node_modules\\@upstash\\context7-mcp\\dist\\index.js"
   ],
   "transport": "stdio"
}

**Comment by ainaerco** [comment]
I think it errors because it can't find index.js, path is not composed correctly on Windows, from logs it tries to load
[context_server::client] context server stderr: Error: Cannot find module 'C:\C:\Users\USER\AppData\Local\Zed\extensions\work\mcp-server-context7\node_modules\@upstash\context7-mcp\dist\index.js'
Obviously, 'C:\C:\' is not a thing.

**Comment by Nabiyevv** [comment]
> I think it errors because it can't find index.js, path is not composed correctly on Windows, from logs it tries to load [context_server::client] context server stderr: Error: Cannot find module 'C:\C:\Users\USER\AppData\Local\Zed\extensions\work\mcp-server-context7\node_modules@upstash\context7-mcp\dist\index.js' Obviously, 'C:\C:' is not a thing.

you can give file path manually like as me.

**Comment by ainaerco** [comment]
With specifying manually, I can see context server and client are running and indicator is green, showing available tools but models are not able to access the provided tool when using use context7 prompt, maybe there's also  something missing on zed side?

**Comment by Nabiyevv** [comment]
Yes, it can be the Zed side. When I try it with Claude 3.5 or 3.7, it works, but it does not work with Gemini 2.0 Flash. I hope they release a Windows version soon.

**Comment by edulml98** [comment]
Hello, now that the windows Zed Nightly version is open

you can add context7, with this config, but only when you add a custom server

```
{
  /// The name of your MCP server
  "context7": {
    /// The command which runs the MCP server
    "command": "cmd",
    /// The arguments to pass to the MCP server
    "args": ["/c","npx","-y","@upstash/context7-mcp","--api-key","YOUR_API_KEY"],
    /// The environment variables to set
    "env": {}
  }
}
```

**Comment by maxbrunsfeld** [comment]
@akbxr The issue is that `std::env::current_dir` returned an invalid path on Windows, until `zed_extension_api` version 0.7.0. https://github.com/akbxr/zed-mcp-server-context7/pull/4 will fix this.
